# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Opportunity Data
email: ross.dakin@pif.gov
description: > # this means to ignore newlines until "baseurl:"
  A collection of resources for developers of tools related to opportunity
  mobility.
baseurl: "" # the subpath of your site, e.g. /blog
email: "opportunity-data@listserv.gsa.gov"
url: "https://ood.pif.gov" # the base hostname & protocol for your site
repo_url: https://github.com/presidential-innovation-fellows/open-opportunity-data

# Build settings
markdown: kramdown

# Play nice with US Design Standards without needing to modify them (drop-in).
sass:
  sass_dir: designstandards/assets/_scss
